{% set name = "py-pde" %}
{% set version = "0.22.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py-pde-{{ version }}.tar.gz
  sha256: b3ab144475e0b0164ee8b1818f34635cbd9aa6e17cb48242c31acda26a622e7c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - matplotlib-base >=3.1
    - numba >=0.56
    - numpy >=1.22
    - python >=3.8
    - scipy >=1.4
    - sympy >=1.5
    - h5py >=2.10
    - pandas >=1.2
    - tqdm >=4.60
    - numba-mpi >=0.13
    - ffmpeg

test:
  imports:
    - pde
    - pde.fields
    - pde.grids
    - pde.pdes
    - pde.solvers
    - pde.storage
    - pde.visualization
    - pde.tools.numba
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zwicker-group/py-pde
  summary: Python package for solving partial differential equations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - volpatto
    - david-zwicker
