{% set name = "py-pde" %}
{% set version = "0.22.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py-pde-{{ version }}.tar.gz
  sha256: 208c583ac7463e06ce93b6d94a74994a987f6478dc9d1dfa917e86f53594f25f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - matplotlib-base >=3.1
    - numba >=0.56
    - numpy >=1.22
    - python >=3.8
    - scipy >=1.4
    - sympy >=1.5
    - h5py >=2.10
    - pandas >=1.2
    - tqdm >=4.60
    - ffmpeg

test:
  imports:
    - pde
    - pde.fields
    - pde.grids
    - pde.pdes
    - pde.solvers
    - pde.storage
    - pde.visualization
    - pde.tools.numba
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zwicker-group/py-pde
  summary: Python package for solving partial differential equations
  license: MIT
  license_file: LICENSE
  doc_url: https://py-pde.readthedocs.io
  description: |
    py-pde is a Python package for solving partial differential equations (PDEs).
    The package provides classes for grids on which scalar and tensor fields can be defined.
    The associated differential operators are computed using a numba-compiled implementation of finite differences.
    This allows defining, inspecting, and solving typical PDEs that appear for instance in the study of dynamical systems in physics.
    The focus of the package lies on easy usage to explore the behavior of PDEs.
    However, core computations can be compiled transparently using numba for speed.

extra:
  recipe-maintainers:
    - volpatto
    - david-zwicker
