{% set name = "py-pde" %}
{% set version = "0.42.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/py_pde-{{ version }}.tar.gz
  sha256: 0d46304bd0a64c977ffa5dd02b5004a07885a1e362c2efc4768327e0e6315f16

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps . -vvv
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - pip
    - setuptools_scm
  run:
    - ffmpeg
    - h5py >=2.10
    - ipywidgets >=8
    - matplotlib-base >=3.1
    - numba >=0.59
    - numpy >=1.22
    - pandas >=2
    - python >=3.9,<3.13
    - scipy >=1.10
    - sympy >=1.9
    - tqdm >=4.66

test:
  requires:
    - pip
  imports:
    - pde
    - pde.fields
    - pde.grids
    - pde.pdes
    - pde.solvers
    - pde.storage
    - pde.visualization
    - pde.tools.numba
  commands:
    - pip check
    # Check whether the pip version is reported correctly
    - pip list | grep -i {{ name }} | grep {{ version }}

about:
  home: https://github.com/zwicker-group/py-pde
  summary: Python package for solving partial differential equations
  license: MIT
  license_file: LICENSE
  doc_url: https://py-pde.readthedocs.io
  description: |
    py-pde is a Python package for solving partial differential equations (PDEs).
    The package provides classes for grids on which scalar and tensor fields can be defined.
    The associated differential operators are computed using a numba-compiled implementation of finite differences.
    This allows defining, inspecting, and solving typical PDEs that appear for instance in the study of dynamical systems in physics.
    The focus of the package lies on easy usage to explore the behavior of PDEs.
    However, core computations can be compiled transparently using numba for speed.

extra:
  recipe-maintainers:
    - volpatto
    - david-zwicker
